server:
  port: 8081
  servlet:
    context-path: /domain
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp